# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.9
FROM ruby:$RUBY_VERSION

WORKDIR /rails

# Install dependencies (lebih lengkap untuk dev)
RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      default-mysql-client \
      default-libmysqlclient-dev \
      git \
      curl \
      libyaml-dev \
      pkg-config && \
    rm -rf /var/lib/apt/lists/*

# ENV khusus development
ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy app
COPY . .

EXPOSE 3000

## Ensure entrypoint executable
RUN chmod +x bin/dev-entrypoint

ENTRYPOINT ["./bin/dev-entrypoint"]

CMD ["./bin/thrust", "./bin/rails", "server", "-b", "0.0.0.0"]