ARG RUBY_VERSION=3.4.9
FROM ruby:$RUBY_VERSION

WORKDIR /rails

# Install base packages
RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      default-mysql-client \
      default-libmysqlclient-dev \
      git \
      curl \
      libyaml-dev \
      pkg-config && \
    rm -rf /var/lib/apt/lists/*

# Set development environment variables
ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

EXPOSE 3000

## Ensure entrypoint executable
RUN chmod +x bin/dev-entrypoint

# Entrypoint setup database
ENTRYPOINT ["./bin/dev-entrypoint"]

# Start server
CMD ["./bin/thrust", "./bin/rails", "server", "-b", "0.0.0.0"]